# Generated by Django 5.1.7 on 2025-03-27 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_joined_date_member_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='joined_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
